export const campusList: string[] = [
  "Dijon",
  "Nancy",
  "Reims",
  "Strasbourg",
  "Châteauroux",
  "Orléans",
  "Paris (La Défense - Nanterre)",
  "Arras",
  "Caen",
  "Lille",
  "Rouen",
  "Angoulême",
  "Brest",
  "La Rochelle",
  "Le Mans",
  "Nantes",
  "Saint-Nazaire",
  "Aix-en-Provence",
  "Grenoble",
  "Lyon",
  "Nice",
  "Bordeaux",
  "Montpellier",
  "Pau",
  "Toulouse",
];
